GET https://fakeserverapi.herokuapp.com/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwiaWF0IjoxNjUzMTEwNTI5LCJleHAiOjE2NTMxMTQxMjksInN1YiI6IjEifQ.wJ-6ckLy7V9l9fbkl963XNk_znoOFfvUQGsUd9sb8RE

### 

PATCH https://fakeserverapi.herokuapp.com/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwiaWF0IjoxNjUzMTEwNTI5LCJleHAiOjE2NTMxMTQxMjksInN1YiI6IjEifQ.wJ-6ckLy7V9l9fbkl963XNk_znoOFfvUQGsUd9sb8RE

{
    "email": "johndoe@email.com",
    "password": "changeme"
}